### ISSUE TITLE
Database seeder for ready to use application 

### ISSUE THREAD

**Issue by Kyuubang** [Kyuubang/shopiea#3]
## Description

Database seeding is a process in which an initial set of data is provided to a database when it is being set up or installed. It's can help application for ready to use without creating the data manually in database.

It's also might be help migrate as containerize application.

## Implementation Model

There are have something to do create seed data, Roles, Admin Users, Class, Course, Labs 

- Roles = admin, student
- Admin Users
- Class = Shopiea
- Course = golang
- Labs = golang-001

## Tasks

- [ ] Create seed data for Roles, Admin Users, Class, Course, Labs 
- [ ] Create Function to migrate databases
- [ ] Migrate to containerize application 
- [ ] Docs to how to use the application
